### ISSUE TITLE
HKAtest

### ISSUE THREAD

**Issue by sheeplin0605** [aguilar-gomez/HKAtest#1]
Hi,

Can you upload the example test data of these three scripts (HKAtest.py,HKAgenes.py and HKAexons.py)? Thanks a lot.

**Comment by aguilar-gomez** [comment]
It is the same format of the file that you need. I added some example files. They are subsets from real files because GitHub has file size limits and is not meant for storage. This is the head of an example file:

> chromo	position	major	minor	ref	anc	knownEM	nInd
> P_RNA_scaffold_2	30316	C	A	C	C	0.000002	26
> P_RNA_scaffold_2	30337	C	A	C	C	0.027999	22
> P_RNA_scaffold_2	30360	T	A	T	T	0.000001	28
> P_RNA_scaffold_2	30394	T	A	T	T	0.000001	29
> P_RNA_scaffold_2	30402	T	A	T	T	0.000000	29
> P_RNA_scaffold_2	30515	A	T	A	A	0.000000	30
> P_RNA_scaffold_2	30580	G	A	G	G	0.000000	30
> P_RNA_scaffold_2	30608	C	A	C	C	0.000000	30
> P_RNA_scaffold_2	30635	G	A	G	G	0.000000	30
